### PR TITLE
Generate bindings using Clang.jl and reimplement C wrappers in Julia

### PR DESCRIPTION
**Pull request by Gnimuc**
This PR implements @eschnett's idea in https://github.com/gridap/MiniQhull.jl/issues/5#issuecomment-725061892.

I did this mainly for testing https://github.com/JuliaInterop/Clang.jl/pull/278, and I do find bugs related to C's bitfields.

### CODE REVIEW

**Comment by eschnett** [comment]
How is the program flow regarding calling `malloc` and `free`? I see that the code calls `malloc`, but never calls `free`. It also seems to me that it would be easy to call `malloc` many times in a program. Do we need an explicit `qhull_handler_free` function? Or could this be handled automatically by registering a finalizer?

**Comment by Gnimuc** [comment]
`Libc.free` is called within `delaunay_free`. When porting the code, I actually hit a problem that there is no `stderr`(be of type `Ptr{FILE}`) in `Libc`.

**Comment by Gnimuc** [comment]
OK, finally got CI passed on macOS. The hard-coded `jmp_buf` should not work on other platforms.

**Comment by Gnimuc** [comment]
Clang.jl can now work in a cross-platform mode. It can download BB's gcc-shards and setup a cross-compile environment(i.e. system headers) to generate bindings for different platforms.

Tests passed on both Linux-x86_64 and macOS, but no luck on Windows. However, I guess the failure on Windows is not due to the wrong size of `qhT`.

@stevengj you might be interested in this.

**Comment by fverdugo** [comment]
Hi @Gnimuc!

I am not convinced if this is the approach we want to adopt to make MiniQHull more portable.

My favorite solution would be to wait until this is taken into account in QHULL : https://github.com/qhull/qhull/issues/86
and, in the mean time, to distribute the MiniQHullWrapper via BinaryBuilder.jl

**Comment by fverdugo** [comment]
I would perhaps invest efforts in distributing the MiniQHullWrapper via BinaryBuilder.jl.

In that way, `MiniQHull` would only depend on `qhull_jll` and `MiniQHullWrapper_jll` (or whatever name we end up with). The letter dependency, could be eventually removed once this https://github.com/qhull/qhull/issues/86 is fixed.

**Comment by Gnimuc** [comment]
Never mind. As I wrote in the OP, the main purpose of this PR is to test the new features of Clang.jl. 

The API of `qhull/qhull` is not designed for the non-C family languages, those macros like `FORALLpoints` are really hard to translate...🤢   I'd say they should provide a whole new set of high-level C APIs.

I'm closing this now, for anyone being interested in auto-generating bindings with Clang.jl, the latest generated code can be always checked at [this link](https://github.com/Gnimuc/GeneratorScripts/tree/master/Q/Qhull).

**Comment by fverdugo** [comment]
Yes, the macros like `FORALLpoints` are the main reason we introduced the C wrappers!

**Comment by Gnimuc** [comment]
What I'm currently experimenting with is that 
1. partially resurrect Cxx.jl, so Julia becomes a "C-family language" and one can do Julia-C interop seamlessly; 
2. create a package for analyzing the code and auto-generating the corresponding C89 wrapper library based on the analysis result; 
3. we definitely don't want to bundle an LLVM/Clang compiler in the release version of our package, so the package should also generate corresponding BB scripts. 

In this way, we can use LLVM/Clang in the dev mode for interactively developing the package and publish the final lightweight release version of the package based on BB artifacts.

**Pull request closed without merging**
